language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=keeper,luna --omit=luna/asgi.py,luna/wsgi.py ./manage.py test keeper.tests
  - coveralls

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
