# Generated by Django 3.2.6 on 2021-08-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pony_id', models.IntegerField(db_index=True)),
                ('create_time', models.DateTimeField()),
                ('previous_status', models.IntegerField()),
                ('current_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('passcode', models.CharField(max_length=255)),
                ('dark_minute', models.IntegerField()),
                ('last_hi_time', models.DateTimeField()),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('notify_channel', models.CharField(max_length=10)),
                ('notify_url', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
