# Generated by Django 3.2.6 on 2021-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='last_hi_time',
            field=models.DateTimeField(null=True),
        ),
    ]
